# Generated by Django 5.1.7 on 2025-04-26 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase de icono')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de gráfico',
                'verbose_name_plural': 'Tipos de gráficos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('layout_config', models.JSONField(blank=True, null=True, verbose_name='Configuración de diseño')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es predeterminado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('models_included', models.JSONField(blank=True, null=True, verbose_name='Modelos incluidos')),
                ('report_config', models.JSONField(blank=True, null=True, verbose_name='Configuración del informe')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Última generación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Informe de datos',
                'verbose_name_plural': 'Informes de datos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('x_axis_field', models.CharField(max_length=100, verbose_name='Campo eje X')),
                ('y_axis_field', models.CharField(max_length=100, verbose_name='Campo eje Y')),
                ('filter_config', models.JSONField(blank=True, null=True, verbose_name='Configuración de filtros')),
                ('chart_config', models.JSONField(blank=True, null=True, verbose_name='Configuración del gráfico')),
                ('color_scheme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Esquema de colores')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es público')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Es favorito')),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.charttype', verbose_name='Tipo de gráfico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('model_content_type', models.ForeignKey(help_text='El modelo de datos que se usa para este gráfico', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Gráfico guardado',
                'verbose_name_plural': 'Gráficos guardados',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posición X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posición Y')),
                ('width', models.IntegerField(default=4, verbose_name='Ancho')),
                ('height', models.IntegerField(default=3, verbose_name='Alto')),
                ('widget_config', models.JSONField(blank=True, null=True, verbose_name='Configuración del widget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard', verbose_name='Dashboard')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('saved_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.savedchart', verbose_name='Gráfico guardado')),
            ],
            options={
                'verbose_name': 'Widget de dashboard',
                'verbose_name_plural': 'Widgets de dashboard',
                'ordering': ['position_y', 'position_x'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_active', '-created_at'], name='dashboard_d_is_acti_51c50e_idx'),
        ),
        migrations.AddIndex(
            model_name='datareport',
            index=models.Index(fields=['is_active', '-created_at'], name='dashboard_d_is_acti_dcb844_idx'),
        ),
        migrations.AddIndex(
            model_name='savedchart',
            index=models.Index(fields=['is_active', '-created_at'], name='dashboard_s_is_acti_1ac8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['is_active', '-created_at'], name='dashboard_d_is_acti_05af1b_idx'),
        ),
    ]
