from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
import time

from apps.base.models.support import City, Country, State

class Command(BaseCommand):
    help = 'Carga datos del Paises, departamentos y ciudades'

    def add_arguments(self, parser):
        parser.add_argument(
            '--level',
            type=str,
            choices=['country', 'state', 'city', 'all'],
            default='all',
            help='Especificar el nivel de datos a cargar: country, state, city o all (todos)'
        )
        
        parser.add_argument(
            '--batch',
            type=int,
            default=100,
            help='Tamaño del lote para carga masiva'
        )

    def handle(self, *args, **options):
        level = options['level']
        batch_size = options['batch']

        start_time = time.time()
        self.stdout.write(self.style.MIGRATE_HEADING(f"Iniciando carga de datos - Nivel: {level}"))

        try:
            if level == 'country' or level == 'all':
                self.load_countries()

            if level == 'state' or level == 'all':
                self.load_states(batch_size)
            
            if level == 'city' or level == 'all':
                self.load_cities(batch_size)
            
            elapsed_time = time.time() - start_time
            self.stdout.write(self.style.SUCCESS(f"✅ Carga completada en {elapsed_time:.2f} segundos"))
        
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"❌ Error en la carga de datos: {str(e)}"))
            raise CommandError(f"❌ La carga de datos falló: {str(e)}")
        
    def load_countries(self):
        """Carga los paises"""
        self.stdout.write("Cargando paises...")
        
        try:
            with transaction.atomic():
                PAISES=[
                    (1, ' Afganistán', 'Afganistán', 'AF', 'AFG', 4, 'afgano/a'),
                    (2, ' Åland', 'Islas Åland', 'AX', 'ALA', 248, 'alandés/esa'),
                    (3, ' Albania', 'Albania', 'AL', 'ALB', 8, 'albanés/esa'),
                    (4, ' Alemania', 'Alemania', 'DE', 'DEU', 276, 'alemán/alemana'),
                    (5, ' Andorra', 'Andorra', 'AD', 'AND', 20, 'andorrano/ana'),
                    (6, ' Angola', 'Angola', 'AO', 'AGO', 24, 'angoleño/ña'),
                    (7, ' Anguila', 'Anguila', 'AI', 'AIA', 660, 'anguilanés/esa'),
                    (8, ' Antártida', 'Antártida', 'AQ', 'ATA', 10, 'antártico/ca'),
                    (9, ' Antigua y Barbuda', 'Antigua y Barbuda', 'AG', 'ATG', 28, 'antiguano/ana'),
                    (10, ' Arabia Saudita', 'Arabia Saudita', 'SA', 'SAU', 682, 'saudí'),
                    (11, ' Argelia', 'Argelia', 'DZ', 'DZA', 12, 'argelino/na'),
                    (12, ' Argentina', 'Argentina', 'AR', 'ARG', 32, 'argentino/na'),
                    (13, ' Armenia', 'Armenia', 'AM', 'ARM', 51, 'armenio/nia'),
                    (14, ' Aruba', 'Aruba', 'AW', 'ABW', 533, 'arubeño/ña'),
                    (15, ' Australia', 'Australia', 'AU', 'AUS', 36, 'australiano/na'),
                    (16, ' Austria', 'Austria', 'AT', 'AUT', 40, 'austriaco/ca'),
                    (17, ' Azerbaiyán', 'Azerbaiyán', 'AZ', 'AZE', 31, 'azerbaiyano/na'),
                    (18, ' Bahamas', 'Bahamas (las)', 'BS', 'BHS', 44, 'bahameño/ña'),
                    (19, ' Bangladés', 'Bangladés', 'BD', 'BGD', 50, 'bangladesí'),
                    (20, ' Barbados', 'Barbados', 'BB', 'BRB', 52, 'barbadense'),
                    (21, ' Baréin', 'Baréin', 'BH', 'BHR', 48, 'bareiní'),
                    (22, ' Bélgica', 'Bélgica', 'BE', 'BEL', 56, 'belga'),
                    (23, ' Belice', 'Belice', 'BZ', 'BLZ', 84, 'beliceño/ña'),
                    (24, ' Benín', 'Benín', 'BJ', 'BEN', 204, 'beninés/esa'),
                    (25, ' Bermudas', 'Bermudas', 'BM', 'BMU', 60, 'bermudeño/ña'),
                    (26, ' Bielorrusia', 'Bielorrusia', 'BY', 'BLR', 112, 'bielorruso/sa'),
                    (27, ' Birmania', 'Myanmar', 'MM', 'MMR', 104, 'birmano/na'),
                    (28, ' Bolivia', 'Bolivia, Estado Plurinacional ', 'BO', 'BOL', 68, 'boliviano/na'),
                    (29, ' Bosnia y Herzegovina', 'Bosnia y Herzegovina', 'BA', 'BIH', 70, 'bosnio/nia'),
                    (30, ' Botsuana', 'Botsuana', 'BW', 'BWA', 72, 'bostuano/ana'),
                    (31, ' Brasil', 'Brasil', 'BR', 'BRA', 76, 'brasileño/ña'),
                    (32, ' Brunéi', 'Brunéi Darussalam', 'BN', 'BRN', 96, 'bruneano/na'),
                    (33, ' Bulgaria', 'Bulgaria', 'BG', 'BGR', 100, 'búlgaro/ra'),
                    (34, ' Burkina Faso', 'Burkina Faso', 'BF', 'BFA', 854, 'burkinés/esa'),
                    (35, ' Burundi', 'Burundi', 'BI', 'BDI', 108, 'burundés/esa'),
                    (36, ' Bután', 'Bután', 'BT', 'BTN', 64, 'butanés/esa'),
                    (37, ' Cabo Verde', 'Cabo Verde', 'CV', 'CPV', 132, 'caboverdiano/na'),
                    (38, ' Camboya', 'Camboya', 'KH', 'KHM', 116, 'camboyano/na'),
                    (39, ' Camerún', 'Camerún', 'CM', 'CMR', 120, 'camerunés/esa'),
                    (40, ' Canadá', 'Canadá', 'CA', 'CAN', 124, 'canadiense'),
                    (41, ' Catar', 'Catar', 'QA', 'QAT', 634, 'catarí'),
                    (42, ' Caribe Neerlandés', 'Bonaire, San Eustaquio y Saba', 'BQ', 'BES', 535, 'caribeño/ña neerlandés/esa'),
                    (43, ' Chad', 'Chad', 'TD', 'TCD', 148, 'chadiano/na'),
                    (44, ' Chile', 'Chile', 'CL', 'CHL', 152, 'chileno/na'),
                    (45, ' China', 'China', 'CN', 'CHN', 156, 'chino/na'),
                    (46, ' Chipre', 'Chipre', 'CY', 'CYP', 196, 'chipriota'),
                    (47, ' Colombia', 'Colombia', 'CO', 'COL', 170, 'colombiano/na'),
                    (48, ' Comoras', 'Comoras', 'KM', 'COM', 174, 'comorense'),
                    (49, ' Corea del Norte', 'Corea (la República Democrática Popular de)', 'KP', 'PRK', 408, 'norcoreano/na'),
                    (50, ' Corea del Sur', 'Corea (la República de)', 'KR', 'KOR', 410, 'surcoreano/na'),
                    (51, ' Costa de Marfil', 'Côte dIvoire', 'CI', 'CIV', 384, 'marfileño/ña'),
                    (52, ' Costa Rica', 'Costa Rica', 'CR', 'CRI', 188, 'costarricense'),
                    (53, ' Croacia', 'Croacia', 'HR', 'HRV', 191, 'croata'),
                    (54, ' Cuba', 'Cuba', 'CU', 'CUB', 192, 'cubano/na'),
                    (55, ' Curazao', 'Curaçao', 'CW', 'CUW', 531, 'curazoleño/ña'),
                    (56, ' Dinamarca', 'Dinamarca', 'DK', 'DNK', 208, 'danés/esa'),
                    (57, ' Dominica', 'Dominica', 'DM', 'DMA', 212, 'dominiqués/esa'),
                    (58, ' Ecuador', 'Ecuador', 'EC', 'ECU', 218, 'ecuatoriano/na'),
                    (59, ' Egipto', 'Egipto', 'EG', 'EGY', 818, 'egipcio/cia'),
                    (60, ' El Salvador', 'El Salvador', 'SV', 'SLV', 222, 'salvadoreño/ña'),
                    (61, ' Emiratos Árabes Unidos', 'Emiratos Árabes Unidos (Los)', 'AE', 'ARE', 784, 'emiratí'),
                    (62, ' Eritrea', 'Eritrea', 'ER', 'ERI', 232, 'eritreo/rea'),
                    (63, ' Eslovaquia', 'Eslovaquia', 'SK', 'SVK', 703, 'eslovaco/ca'),
                    (64, ' Eslovenia', 'Eslovenia', 'SI', 'SVN', 705, 'esloveno/na'),
                    (65, ' España', 'España', 'ES', 'ESP', 724, 'español/ola'),
                    (66, ' Estados Unidos', 'Estados Unidos (los)', 'US', 'USA', 840, 'estadounidense'),
                    (67, ' Estonia', 'Estonia', 'EE', 'EST', 233, 'estonio/nia'),
                    (68, ' Etiopía', 'Etiopía', 'ET', 'ETH', 231, 'etíope'),
                    (69, ' Filipinas', 'Filipinas (las)', 'PH', 'PHL', 608, 'filipino/na'),
                    (70, ' Finlandia', 'Finlandia', 'FI', 'FIN', 246, 'finlandés/esa'),
                    (71, ' Fiyi', 'Fiyi', 'FJ', 'FJI', 242, 'fiyiano/na'),
                    (72, ' Francia', 'Francia', 'FR', 'FRA', 250, 'francés/esa'),
                    (73, ' Gabón', 'Gabón', 'GA', 'GAB', 266, 'gabonés/esa'),
                    (74, ' Gambia', 'Gambia (La)', 'GM', 'GMB', 270, 'gambiano/na'),
                    (75, ' Georgia', 'Georgia', 'GE', 'GEO', 268, 'georgiano/na'),
                    (76, ' Ghana', 'Ghana', 'GH', 'GHA', 288, 'ghanés/esa'),
                    (77, ' Gibraltar', 'Gibraltar', 'GI', 'GIB', 292, 'gibraltareño/ña'),
                    (78, ' Granada', 'Granada', 'GD', 'GRD', 308, 'granadino/na'),
                    (79, ' Grecia', 'Grecia', 'GR', 'GRC', 300, 'griego/griega'),
                    (80, ' Groenlandia', 'Groenlandia', 'GL', 'GRL', 304, 'groenlandés/esa'),
                    (81, ' Guadalupe', 'Guadalupe', 'GP', 'GLP', 312, 'guadalupeño/ña'),
                    (82, ' Guam', 'Guam', 'GU', 'GUM', 316, 'guameño/ña'),
                    (83, ' Guatemala', 'Guatemala', 'GT', 'GTM', 320, 'guatemalteco/ca'),
                    (84, ' Guayana Francesa', 'Guayana Francesa', 'GF', 'GUF', 254, 'guayanés/esa'),
                    (85, ' Guernsey', 'Guernsey', 'GG', 'GGY', 831, 'guernés/esa'),
                    (86, ' Guinea', 'Guinea', 'GN', 'GIN', 324, 'guineano/na'),
                    (87, ' Guinea-Bisáu', 'Guinea-Bisáu', 'GW', 'GNB', 624, 'guineano-bisauano/na'),
                    (88, ' Guinea Ecuatorial', 'Guinea Ecuatorial', 'GQ', 'GNQ', 226, 'ecuatoguineano/na'),
                    (89, ' Guyana', 'Guyana', 'GY', 'GUY', 328, 'guyanés/esa'),
                    (90, ' Haití', 'Haití', 'HT', 'HTI', 332, 'haitiano/na'),
                    (91, ' Honduras', 'Honduras', 'HN', 'HND', 340, 'hondureño/ña'),
                    (92, ' Hong Kong', 'Hong Kong', 'HK', 'HKG', 344, 'hongkonés/esa'),
                    (93, ' Hungría', 'Hungría', 'HU', 'HUN', 348, 'húngaro/ra'),
                    (94, ' India', 'India', 'IN', 'IND', 356, 'indio/nia'),
                    (95, ' Indonesia', 'Indonesia', 'ID', 'IDN', 360, 'indonesio/nia'),
                    (96, ' Irak', 'Irak', 'IQ', 'IRQ', 368, 'iraquí'),
                    (97, ' Irán', 'Irán (la República Islámica de', 'IR', 'IRN', 364, 'iraní'),
                    (98, ' Irlanda', 'Irlanda', 'IE', 'IRL', 372, 'irlandés/esa'),
                    (99, ' Isla Bouvet', 'Isla Bouvet', 'BV', 'BVT', 74, 'bouvetiano/na'),
                    (100, ' Isla de Man', 'Isla de Man', 'IM', 'IMN', 833, 'manés/esa'),
                    (101, ' Isla de Navidad', 'Isla de Navidad', 'CX', 'CXR', 162, 'navideño/ña'),
                    (102, ' Norfolk', 'Isla Norfolk', 'NF', 'NFK', 574, 'norfolkense'),
                    (103, ' Islandia', 'Islandia', 'IS', 'ISL', 352, 'islandés/esa'),
                    (104, ' Islas Caimán', 'Islas Caimán (las)', 'KY', 'CYM', 136, 'caimánense'),
                    (105, ' Islas Cocos', 'Islas Cocos (Keeling)', 'CC', 'CCK', 166, 'cocoense'),
                    (106, ' Islas Cook', 'Islas Cook (las)', 'CK', 'COK', 184, 'cookiano/na'),
                    (107, ' Islas Feroe', 'Islas Feroe (las)', 'FO', 'FRO', 234, 'feroés/esa'),
                    (108, ' Islas Georgias del Sur y Sand', 'Georgia del sur y las islas sa', 'GS', 'SGS', 239, 'georgiano/na del sur'),
                    (109, ' Islas Heard y McDonald', 'Isla Heard e Islas McDonald', 'HM', 'HMD', 334, 'heardense'),
                    (110, ' Islas Malvinas', 'Islas Malvinas [Falkland] (las', 'FK', 'FLK', 238, 'malvinense'),
                    (111, ' Islas Marianas del Norte', 'Islas Marianas del Norte (las)', 'MP', 'MNP', 580, 'marianense'),
                    (112, ' Islas Marshall', 'Islas Marshall (las)', 'MH', 'MHL', 584, 'marshalés/esa'),
                    (113, ' Islas Pitcairn', 'Pitcairn', 'PN', 'PCN', 612, 'pitcairnense'),
                    (114, ' Islas Salomón', 'Islas Salomón (las)', 'SB', 'SLB', 90, 'salomonense'),
                    (115, ' Islas Turcas y Caicos', 'Islas Turcas y Caicos (las)', 'TC', 'TCA', 796, 'turqués/esa'),
                    (116, ' Islas ultramarinas de Estados', 'Islas de Ultramar Menores de E', 'UM', 'UMI', 581, 'estadounidense'),
                    (117, ' Islas Vírgenes Británicas', 'Islas Vírgenes (Británicas)', 'VG', 'VGB', 92, 'virgenense'),
                    (118, ' Islas Vírgenes de los Estados', 'Islas Vírgenes (EE.UU.)', 'VI', 'VIR', 850, 'virgenense'),
                    (119, ' Israel', 'Israel', 'IL', 'ISR', 376, 'israelí'),
                    (120, ' Italia', 'Italia', 'IT', 'ITA', 380, 'italiano/na'),
                    (121, ' Jamaica', 'Jamaica', 'JM', 'JAM', 388, 'jamaiquino/na'),
                    (122, ' Japón', 'Japón', 'JP', 'JPN', 392, 'japonés/esa'),
                    (123, ' Jersey', 'Jersey', 'JE', 'JEY', 832, 'jersiano/na'),
                    (124, ' Jordania', 'Jordania', 'JO', 'JOR', 400, 'jordano/na'),
                    (125, ' Kazajistán', 'Kazajistán', 'KZ', 'KAZ', 398, 'kazajo/ja'),
                    (126, ' Kenia', 'Kenia', 'KE', 'KEN', 404, 'keniano/na'),
                    (127, ' Kirguistán', 'Kirguistán', 'KG', 'KGZ', 417, 'kirguís'),
                    (128, ' Kiribati', 'Kiribati', 'KI', 'KIR', 296, 'kiribatiano/na'),
                    (129, ' Kuwait', 'Kuwait', 'KW', 'KWT', 414, 'kuwaití'),
                    (130, ' Laos', 'Lao, (la) República Democrática Popular de', 'LA', 'LAO', 418, 'laosiano/na'),
                    (131, ' Lesoto', 'Lesoto', 'LS', 'LSO', 426, 'lesotense'),
                    (132, ' Letonia', 'Letonia', 'LV', 'LVA', 428, 'letón/ona'),
                    (133, ' Líbano', 'Líbano', 'LB', 'LBN', 422, 'libanés/esa'),
                    (134, ' Liberia', 'Liberia', 'LR', 'LBR', 430, 'liberiano/na'),
                    (135, ' Libia', 'Libia', 'LY', 'LBY', 434, 'libio/bia'),
                    (136, ' Liechtenstein', 'Liechtenstein', 'LI', 'LIE', 438, 'liechtensteiniano/na'),
                    (137, ' Lituania', 'Lituania', 'LT', 'LTU', 440, 'lituano/na'),
                    (138, ' Luxemburgo', 'Luxemburgo', 'LU', 'LUX', 442, 'luxemburgués/sa'),
                    (139, ' Macao', 'Macao', 'MO', 'MAC', 446, 'macaense'),
                    (140, ' Madagascar', 'Madagascar', 'MG', 'MDG', 450, 'malgache'),
                    (141, ' Malasia', 'Malasia', 'MY', 'MYS', 458, 'malasio/sia'),
                    (142, ' Malaui', 'Malaui', 'MW', 'MWI', 454, 'malauí'),
                    (143, ' Maldivas', 'Maldivas', 'MV', 'MDV', 462, 'maldivo/va'),
                    (144, ' Malí', 'Malí', 'ML', 'MLI', 466, 'maliense'),
                    (145, ' Malta', 'Malta', 'MT', 'MLT', 470, 'maltés/sa'),
                    (146, ' Marruecos', 'Marruecos', 'MA', 'MAR', 504, 'marroquí'),
                    (147, ' Martinica', 'Martinica', 'MQ', 'MTQ', 474, 'martiniqués/sa'),
                    (148, ' Mauricio', 'Mauricio', 'MU', 'MUS', 480, 'mauriciano/na'),
                    (149, ' Mauritania', 'Mauritania', 'MR', 'MRT', 478, 'mauritano/na'),
                    (150, ' Mayotte', 'Mayotte', 'YT', 'MYT', 175, 'mahorés/sa'),
                    (151, ' México', 'México', 'MX', 'MEX', 484, 'mexicano/na'),
                    (152, ' Micronesia', 'Micronesia (los Estados Federa', 'FM', 'FSM', 583, 'micronesio/sia'),
                    (153, ' Moldavia', 'Moldavia (la República de)', 'MD', 'MDA', 498, 'moldavo/va'),
                    (154, ' Mónaco', 'Mónaco', 'MC', 'MCO', 492, 'monegasco/ca'),
                    (155, ' Mongolia', 'Mongolia', 'MN', 'MNG', 496, 'mongol/ola'),
                    (156, ' Montenegro', 'Montenegro', 'ME', 'MNE', 499, 'montenegrino/na'),
                    (157, ' Montserrat', 'Montserrat', 'MS', 'MSR', 500, 'montserratiano/na'),
                    (158, ' Mozambique', 'Mozambique', 'MZ', 'MOZ', 508, 'mozambiqueño/ña'),
                    (159, ' Namibia', 'Namibia', 'NA', 'NAM', 516, 'namibio/bia'),
                    (160, ' Nauru', 'Nauru', 'NR', 'NRU', 520, 'nauruano/na'),
                    (161, ' Nepal', 'Nepal', 'NP', 'NPL', 524, 'nepalí'),
                    (162, ' Nicaragua', 'Nicaragua', 'NI', 'NIC', 558, 'nicaragüense'),
                    (163, ' Níger', 'Níger (el)', 'NE', 'NER', 562, 'nigerino/na'),
                    (164, ' Nigeria', 'Nigeria', 'NG', 'NGA', 566, 'nigeriano/na'),
                    (165, ' Niue', 'Niue', 'NU', 'NIU', 570, 'niuano/na'),
                    (166, ' Noruega', 'Noruega', 'NO', 'NOR', 578, 'noruego/ga'),
                    (167, ' Nueva Caledonia', 'Nueva Caledonia', 'NC', 'NCL', 540, 'neocaledonio/nia'),
                    (168, ' Nueva Zelanda', 'Nueva Zelanda', 'NZ', 'NZL', 554, 'neozelandés/esa'),
                    (169, ' Omán', 'Omán', 'OM', 'OMN', 512, 'omani'),
                    (170, ' Países Bajos', 'Países Bajos (los)', 'NL', 'NLD', 528, 'neerlandés/esa'),
                    (171, ' Pakistán', 'Pakistán', 'PK', 'PAK', 586, 'paquistaní'),
                    (172, ' Palaos', 'Palaos', 'PW', 'PLW', 585, 'palaosiano/na'),
                    (173, ' Palestina', 'Palestina, Estado de', 'PS', 'PSE', 275, 'palestino/na'),
                    (174, ' Panamá', 'Panamá', 'PA', 'PAN', 591, 'panameño/ña'),
                    (175, ' Papúa Nueva Guinea', 'Papúa Nueva Guinea', 'PG', 'PNG', 598, 'papú/pua neoguineano/na'),
                    (176, ' Paraguay', 'Paraguay', 'PY', 'PRY', 600, 'paraguayo/ya'),
                    (177, ' Perú', 'Perú', 'PE', 'PER', 604, 'peruano/na'),
                    (178, ' Polinesia Francesa', 'Polinesia Francesa', 'PF', 'PYF', 258, 'polinesio/sia francés/esa'),
                    (179, ' Polonia', 'Polonia', 'PL', 'POL', 616, 'polaco/ca'),
                    (180, ' Portugal', 'Portugal', 'PT', 'PRT', 620, 'portugués/esa'),
                    (181, ' Puerto Rico', 'Puerto Rico', 'PR', 'PRI', 630, 'puertorriqueño/ña'),
                    (182, ' Reino Unido', 'Reino Unido (el)', 'GB', 'GBR', 826, 'británico/ca'),
                    (183, ' República Centroafricana', 'República Centroafricana (la)', 'CF', 'CAF', 140, 'centroafricano/na'),
                    (184, ' República Checa', 'República Checa (la)', 'CZ', 'CZE', 203, 'checo/ca'),
                    (185, ' Macedonia', 'Macedonia (la antigua República', 'MK', 'MKD', 807, 'macedonio/nia'),
                    (186, ' República del Congo', 'Congo', 'CG', 'COG', 178, 'congoleño/ña'),
                    (187, ' República Democrática del Congo', 'Congo (la República Democrática del)', 'CD', 'COD', 180, 'congoleño/ña'),
                    (188, ' República Dominicana', 'República Dominicana (la)', 'DO', 'DOM', 214, 'dominicano/na'),
                    (189, ' Reunión', 'Reunión', 'RE', 'REU', 638, 'reunionés/esa'),
                    (190, ' Ruanda', 'Ruanda', 'RW', 'RWA', 646, 'ruandés/esa'),
                    (191, ' Rumania', 'Rumania', 'RO', 'ROU', 642, 'rumano/na'),
                    (192, ' Rusia', 'Rusia, (la) Federación de', 'RU', 'RUS', 643, 'ruso/sa'),
                    (193, ' República Árabe Saharaui Democrática', 'Sahara Occidental', 'EH', 'ESH', 732, 'saharaui'),
                    (194, ' Samoa', 'Samoa', 'WS', 'WSM', 882, 'samoano/na'),
                    (195, ' Samoa Americana', 'Samoa Americana', 'AS', 'ASM', 16, 'samoano/na americano/na'),
                    (196, ' San Bartolomé', 'San Bartolomé', 'BL', 'BLM', 652, 'bartolomeano/na'),
                    (197, ' San Cristóbal y Nieves', 'San Cristóbal y Nieves', 'KN', 'KNA', 659, 'sanvicentino/na'),
                    (198, ' San Marino', 'San Marino', 'SM', 'SMR', 674, 'sanmarinense'),
                    (199, ' San Martín', 'San Martín (parte francesa)', 'MF', 'MAF', 663, 'sanmartinense'),
                    (200, ' San Pedro y Miquelón', 'San Pedro y Miquelón', 'PM', 'SPM', 666, 'sanpedriano/na'),
                    (201, ' San Vicente y las Granadinas', 'San Vicente y las Granadinas', 'VC', 'VCT', 670, 'sanvicentino/na'),
                    (202, ' Santa Elena, Ascensión y Tristán de Acuña', 'Santa Elena, Ascensión y Tristán de Acuña', 'SH', 'SHN', 654, 'santaelenense'),
                    (203, ' Santa Lucía', 'Santa Lucía', 'LC', 'LCA', 662, 'santaluciano/na'),
                    (204, ' Santo Tomé y Príncipe', 'Santo Tomé y Príncipe', 'ST', 'STP', 678, 'santotomense'),
                    (205, ' Senegal', 'Senegal', 'SN', 'SEN', 686, 'senegalés/esa'),
                    (206, ' Serbia', 'Serbia', 'RS', 'SRB', 688, 'serbio/bia'),
                    (207, ' Seychelles', 'Seychelles', 'SC', 'SYC', 690, 'seychellense'),
                    (208, ' Sierra Leona', 'Sierra leona', 'SL', 'SLE', 694, 'sierraleonés/esa'),
                    (209, ' Singapur', 'Singapur', 'SG', 'SGP', 702, 'singapurense'),
                    (210, ' Sint Maarten', 'Sint Maarten (parte holandesa)', 'SX', 'SXM', 534, 'sintmaartense'),
                    (211, ' Siria', 'Siria, (la) República Árabe', 'SY', 'SYR', 760, 'sirio/ria'),
                    (212, ' Somalia', 'Somalia', 'SO', 'SOM', 706, 'somalí'),
                    (213, ' Sri Lanka', 'Sri Lanka', 'LK', 'LKA', 144, 'ceilanés/esa'),
                    (214, ' Suazilandia', 'Suazilandia', 'SZ', 'SWZ', 748, 'suazi'),
                    (215, ' Sudáfrica', 'Sudáfrica', 'ZA', 'ZAF', 710, 'sudafricano/na'),
                    (216, ' Sudán', 'Sudán (el)', 'SD', 'SDN', 729, 'sudanés/esa'),
                    (217, ' Sudán del Sur', 'Sudán del Sur', 'SS', 'SSD', 728, 'sursudanés/esa'),
                    (218, ' Suecia', 'Suecia', 'SE', 'SWE', 752, 'sueco/ca'),
                    (219, '  Suiza', 'Suiza', 'CH', 'CHE', 756, 'suizo/za'),
                    (220, ' Surinam', 'Surinam', 'SR', 'SUR', 740, 'surinamés/esa'),
                    (221, ' Svalbard y Jan Mayen', 'Svalbard y Jan Mayen', 'SJ', 'SJM', 744, 'svalbardiano/na'),
                    (222, ' Tailandia', 'Tailandia', 'TH', 'THA', 764, 'tailandés/esa'),
                    (223, ' República de China', 'Taiwán (Provincia de China)', 'TW', 'TWN', 158, 'taiwanés/esa'),
                    (224, ' Tanzania', 'Tanzania, República Unida de', 'TZ', 'TZA', 834, 'tanzano/na'),
                    (225, ' Tayikistán', 'Tayikistán', 'TJ', 'TJK', 762, 'tayiko/ka'),
                    (226, ' Territorio Británico del Océano Índico', 'Territorio Británico del Océano Índico', 'IO', 'IOT', 86, 'británico/ca'),
                    (227, ' Tierras Australes y Antárticas Francesas', 'Territorios Australes Franceses', 'TF', 'ATF', 260, 'francés/esa'),
                    (228, ' Timor Oriental', 'Timor-Leste', 'TL', 'TLS', 626, 'timorense'),
                    (229, ' Togo', 'Togo', 'TG', 'TGO', 768, 'togolés/esa'),
                    (230, ' Tokelau', 'Tokelau', 'TK', 'TKL', 772, 'tokelauano/na'),
                    (231, ' Tonga', 'Tonga', 'TO', 'TON', 776, 'tongano/na'),
                    (232, ' Trinidad y Tobago', 'Trinidad y Tobago', 'TT', 'TTO', 780, 'trinitense'),
                    (233, ' Túnez', 'Túnez', 'TN', 'TUN', 788, 'tunecino/na'),
                    (234, ' Turkmenistán', 'Turkmenistán', 'TM', 'TKM', 795, 'turcomano/na'),
                    (235, ' Turquía', 'Turquía', 'TR', 'TUR', 792, 'turco/ca'),
                    (236, ' Tuvalu', 'Tuvalu', 'TV', 'TUV', 798, 'tuvaluano/na'),
                    (237, ' Ucrania', 'Ucrania', 'UA', 'UKR', 804, 'ucraniano/na'),
                    (238, ' Uganda', 'Uganda', 'UG', 'UGA', 800, 'ugandés/esa'),
                    (239, ' Uruguay', 'Uruguay', 'UY', 'URY', 858, 'uruguayo/ya'),
                    (240, ' Uzbekistán', 'Uzbekistán', 'UZ', 'UZB', 860, 'uzbeko/ka'),
                    (241, ' Vanuatu', 'Vanuatu', 'VU', 'VUT', 548, 'vanuatuense'),
                    (242, ' Ciudad del Vaticano', 'Santa Sede [Estado de la Ciudad del Vaticano]', 'VA', 'VAT', 336, 'vaticano/na'),
                    (243, ' Venezuela', 'Venezuela, República Bolivariana de', 'VE', 'VEN', 862, 'venezolano/na'),
                    (244, ' Vietnam', 'Viet Nam', 'VN', 'VNM', 704, 'vietnamita'),
                    (245, ' Wallis y Futuna', 'Wallis y Futuna', 'WF', 'WLF', 876, 'wallisiano/na'),
                    (246, ' Yemen', 'Yemen', 'YE', 'YEM', 887, 'yemení'),
                    (247, ' Yibuti', 'Yibuti', 'DJ', 'DJI', 262, 'yibutiano/na'),
                    (248, ' Zambia', 'Zambia', 'ZM', 'ZMB', 894, 'zambiano/na'),
                    (249, ' Zimbabue', 'Zimbabue', 'ZW', 'ZWE', 716, 'zimbabuense'),

                ]                

                cont = 0
                for id, name, iso_name, alfa2, alfa3, code, demonym in PAISES:
                    _, created = Country.objects.get_or_create(
                        id=id,
                        name=name,
                        iso_name=iso_name,
                        alfa2=alfa2,
                        alfa3=alfa3,
                        code=code,
                        demonym=demonym
                    )
                    if created:
                        cont += 1
                self.stdout.write(self.style.SUCCESS(
                    f'✅ Pais {id} creado correctamente'
                    ))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'❌ Error creando pais: {str(e)}'))
            raise
    
    def load_states(self, batch_size=100):
        """Carga de departamentos/estados"""
        self.stdout.write(self.style.SUCCESS('Cargando departamentos/estados...'))
        
        try:
            with transaction.atomic():
                # Obtener todos los países disponibles
                countries = {country.id: country for country in Country.objects.all()}
                
                if not countries:
                    self.stdout.write(self.style.ERROR(
                        '❌ No hay países disponibles. Ejecuta load_countries primero.'
                    ))
                    return
                    
                DEPARTAMENTOS = [                    
                    (5, 'ANTIOQUIA', 47),
                    (8, 'ATLÁNTICO', 47),
                    (11, 'BOGOTÁ, D.C.', 47),
                    (13, 'BOLÍVAR', 47),
                    (15, 'BOYACÁ', 47),
                    (17, 'CALDAS', 47),
                    (18, 'CAQUETÁ', 47),
                    (19, 'CAUCA', 47),
                    (20, 'CESAR', 47),
                    (23, 'CÓRDOBA', 47),
                    (25, 'CUNDINAMARCA', 47),
                    (27, 'CHOCÓ', 47),
                    (41, 'HUILA', 47),
                    (44, 'LA GUAJIRA', 47),
                    (47, 'MAGDALENA', 47),
                    (50, 'META', 47),
                    (52, 'NARIÑO', 47),
                    (54, 'NORTE DE SANTANDER', 47),
                    (63, 'QUINDIO', 47),
                    (66, 'RISARALDA', 47),
                    (68, 'SANTANDER', 47),
                    (70, 'SUCRE', 47),
                    (73, 'TOLIMA', 47),
                    (76, 'VALLE DEL CAUCA', 47),
                    (81, 'ARAUCA', 47),
                    (85, 'CASANARE', 47),
                    (86, 'PUTUMAYO', 47),
                    (88, 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 47),
                    (91, 'AMAZONAS', 47),
                    (94, 'GUAINÍA', 47),
                    (95, 'GUAVIARE', 47),
                    (97, 'VAUPÉS', 47),
                    (99, 'VICHADA', 47),
                ]
                
                # Agrupar por país para reportes
                departamentos_por_pais = {}
                for _, _, country_id in DEPARTAMENTOS:
                    departamentos_por_pais[country_id] = departamentos_por_pais.get(country_id, 0) + 1
                    
                # Estadísticas por país
                stats_por_pais = {country_id: {'nuevas': 0, 'actualizadas': 0, 'errores': 0} 
                                for country_id in departamentos_por_pais.keys()}
                
                # Procesar por lotes
                for i in range(0, len(DEPARTAMENTOS), batch_size):
                    batch = DEPARTAMENTOS[i:i + batch_size]
                    
                    for code, name, country_id in batch:
                        try:
                            # Verificar que el país existe
                            if country_id not in countries:
                                self.stdout.write(self.style.WARNING(
                                    f'⚠️ País con ID {country_id} no encontrado. Saltando {name}.'
                                ))
                                stats_por_pais.setdefault(country_id, {'nuevas': 0, 'actualizadas': 0, 'errores': 0})
                                stats_por_pais[country_id]['errores'] += 1
                                continue
                                
                            # Convertir código a string con padding de 2 dígitos
                            code_str = str(code).zfill(2)
                            
                            obj, created = State.objects.update_or_create(
                                code=code_str,
                                country=countries[country_id],
                                defaults={
                                    'name': name.upper(),
                                }
                            )
                            
                            if created:
                                stats_por_pais[country_id]['nuevas'] += 1
                                self.stdout.write(f'✅ Creado: {code_str} - {name} ({countries[country_id].name})')
                            else:
                                stats_por_pais[country_id]['actualizadas'] += 1
                                self.stdout.write(f'↻ Actualizado: {code_str} - {name} ({countries[country_id].name})')
                                
                        except Exception as e:
                            stats_por_pais.setdefault(country_id, {'nuevas': 0, 'actualizadas': 0, 'errores': 0})
                            stats_por_pais[country_id]['errores'] += 1
                            self.stdout.write(self.style.ERROR(
                                f'❌ Error en {code_str} {name}: {str(e)}'
                            ))
                    
                    self.stdout.write(f'Procesado lote {(i//batch_size)+1}/{(len(DEPARTAMENTOS)//batch_size)+1}')
                
                # Mostrar resumen por país
                self.stdout.write(self.style.SUCCESS('\n✅ Resumen por país:'))
                for country_id, stats in stats_por_pais.items():
                    country_name = countries.get(country_id, f"ID: {country_id} (No encontrado)")
                    if isinstance(country_name, Country):
                        country_name = country_name.name
                        
                    self.stdout.write(self.style.SUCCESS(
                        f'{country_name}: {stats["nuevas"]} nuevos, {stats["actualizadas"]} actualizados, {stats["errores"]} errores'
                    ))
        
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'🚨 Error global: {str(e)}'))
            raise

    def load_cities(self, batch_size=100):
        """Carga de municipios/ciudades"""
        self.stdout.write(self.style.SUCCESS('Cargando municipios/ciudades...'))

        try:
            with transaction.atomic():
                # Precargar estados (códigos como strings)
                estados = {e.code: e for e in State.objects.all()}
                
                if not estados:
                    self.stdout.write(self.style.ERROR(
                        '⚠️ No hay estados disponibles. Ejecuta load_states primero.'
                    ))
                    return

                MUNICIPIOS = [
                    (1,'Abriaquí',1,5),
                    (2,'Acacías',1,50),
                    (3,'Acandí',1,27),
                    (4,'Acevedo',1,41),
                    (5,'Achí',1,13),
                    (6,'Agrado',1,41),
                    (7,'Agua de Dios',1,25),
                    (8,'Aguachica',1,20),
                    (9,'Aguada',1,68),
                    (10,'Aguadas',1,17),
                    (11,'Aguazul',1,85),
                    (12,'Agustín Codazzi',1,20),
                    (13,'Aipe',1,41),
                    (14,'Albania',1,18),
                    (15,'Albania',1,44),
                    (16,'Albania',1,68),
                    (17,'Albán',1,25),
                    (18,'Albán (San José)',1,52),
                    (19,'Alcalá',1,76),
                    (20,'Alejandria',1,5),
                    (21,'Algarrobo',1,47),
                    (22,'Algeciras',1,41),
                    (23,'Almaguer',1,19),
                    (24,'Almeida',1,15),
                    (25,'Alpujarra',1,73),
                    (26,'Altamira',1,41),
                    (27,'Alto Baudó (Pie de Pato)',1,27),
                    (28,'Altos del Rosario',1,13),
                    (29,'Alvarado',1,73),
                    (30,'Amagá',1,5),
                    (31,'Amalfi',1,5),
                    (32,'Ambalema',1,73),
                    (33,'Anapoima',1,25),
                    (34,'Ancuya',1,52),
                    (35,'Andalucía',1,76),
                    (36,'Andes',1,5),
                    (37,'Angelópolis',1,5),
                    (38,'Angostura',1,5),
                    (39,'Anolaima',1,25),
                    (40,'Anorí',1,5),
                    (41,'Anserma',1,17),
                    (42,'Ansermanuevo',1,76),
                    (43,'Anzoátegui',1,73),
                    (44,'Anzá',1,5),
                    (45,'Apartadó',1,5),
                    (46,'Apulo',1,25),
                    (47,'Apía',1,66),
                    (48,'Aquitania',1,15),
                    (49,'Aracataca',1,47),
                    (50,'Aranzazu',1,17),
                    (51,'Aratoca',1,68),
                    (52,'Arauca',1,81),
                    (53,'Arauquita',1,81),
                    (54,'Arbeláez',1,25),
                    (55,'Arboleda (Berruecos)',1,52),
                    (56,'Arboledas',1,54),
                    (57,'Arboletes',1,5),
                    (58,'Arcabuco',1,15),
                    (59,'Arenal',1,13),
                    (60,'Argelia',1,5),
                    (61,'Argelia',1,19),
                    (62,'Argelia',1,76),
                    (63,'Ariguaní (El Difícil)',1,47),
                    (64,'Arjona',1,13),
                    (65,'Armenia',1,5),
                    (66,'Armenia',1,63),
                    (67,'Armero (Guayabal)',1,73),
                    (68,'Arroyohondo',1,13),
                    (69,'Astrea',1,20),
                    (70,'Ataco',1,73),
                    (71,'Atrato (Yuto)',1,27),
                    (72,'Ayapel',1,23),
                    (73,'Bagadó',1,27),
                    (74,'Bahía Solano (Mútis)',1,27),
                    (75,'Bajo Baudó (Pizarro)',1,27),
                    (76,'Balboa',1,19),
                    (77,'Balboa',1,66),
                    (78,'Baranoa',1,8),
                    (79,'Baraya',1,41),
                    (80,'Barbacoas',1,52),
                    (81,'Barbosa',1,5),
                    (82,'Barbosa',1,68),
                    (83,'Barichara',1,68),
                    (84,'Barranca de Upía',1,50),
                    (85,'Barrancabermeja',1,68),
                    (86,'Barrancas',1,44),
                    (87,'Barranco de Loba',1,13),
                    (88,'Barranquilla',1,8),
                    (89,'Becerríl',1,20),
                    (90,'Belalcázar',1,17),
                    (91,'Bello',1,5),
                    (92,'Belmira',1,5),
                    (93,'Beltrán',1,25),
                    (94,'Belén',1,15),
                    (95,'Belén',1,52),
                    (96,'Belén de Bajirá',1,27),
                    (97,'Belén de Umbría',1,66),
                    (98,'Belén de los Andaquíes',1,18),
                    (99,'Berbeo',1,15),
                    (100,'Betania',1,5),
                    (101,'Beteitiva',1,15),
                    (102,'Betulia',1,5),
                    (103,'Betulia',1,68),
                    (104,'Bituima',1,25),
                    (105,'Boavita',1,15),
                    (106,'Bochalema',1,54),
                    (107,'Bogotá D.C.',1,11),
                    (108,'Bojacá',1,25),
                    (109,'Bojayá (Bellavista)',1,27),
                    (110,'Bolívar',1,5),
                    (111,'Bolívar',1,19),
                    (112,'Bolívar',1,68),
                    (113,'Bolívar',1,76),
                    (114,'Bosconia',1,20),
                    (115,'Boyacá',1,15),
                    (116,'Briceño',1,5),
                    (117,'Briceño',1,15),
                    (118,'Bucaramanga',1,68),
                    (119,'Bucarasica',1,54),
                    (120,'Buenaventura',1,76),
                    (121,'Buenavista',1,15),
                    (122,'Buenavista',1,23),
                    (123,'Buenavista',1,63),
                    (124,'Buenavista',1,70),
                    (125,'Buenos Aires',1,19),
                    (126,'Buesaco',1,52),
                    (127,'Buga',1,76),
                    (128,'Bugalagrande',1,76),
                    (129,'Burítica',1,5),
                    (130,'Busbanza',1,15),
                    (131,'Cabrera',1,25),
                    (132,'Cabrera',1,68),
                    (133,'Cabuyaro',1,50),
                    (134,'Cachipay',1,25),
                    (135,'Caicedo',1,5),
                    (136,'Caicedonia',1,76),
                    (137,'Caimito',1,70),
                    (138,'Cajamarca',1,73),
                    (139,'Cajibío',1,19),
                    (140,'Cajicá',1,25),
                    (141,'Calamar',1,13),
                    (142,'Calamar',1,95),
                    (143,'Calarcá',1,63),
                    (144,'Caldas',1,5),
                    (145,'Caldas',1,15),
                    (146,'Caldono',1,19),
                    (147,'California',1,68),
                    (148,'Calima (Darién)',1,76),
                    (149,'Caloto',1,19),
                    (150,'Cali',1,76),
                    (151,'Campamento',1,5),
                    (152,'Campo de la Cruz',1,8),
                    (153,'Campoalegre',1,41),
                    (154,'Campohermoso',1,15),
                    (155,'Canalete',1,23),
                    (156,'Candelaria',1,8),
                    (157,'Candelaria',1,76),
                    (158,'Cantagallo',1,13),
                    (159,'Cantón de San Pablo',1,27),
                    (160,'Caparrapí',1,25),
                    (161,'Capitanejo',1,68),
                    (162,'Caracolí',1,5),
                    (163,'Caramanta',1,5),
                    (164,'Carcasí',1,68),
                    (165,'Carepa',1,5),
                    (166,'Carmen de Apicalá',1,73),
                    (167,'Carmen de Carupa',1,25),
                    (168,'Carmen de Viboral',1,5),
                    (169,'Carmen del Darién (CURBARADÓ)',1,27),
                    (170,'Carolina',1,5),
                    (171,'Cartagena',1,13),
                    (172,'Cartagena del Chairá',1,18),
                    (173,'Cartago',1,76),
                    (174,'Carurú',1,97),
                    (175,'Casabianca',1,73),
                    (176,'Castilla la Nueva',1,50),
                    (177,'Caucasia',1,5),
                    (178,'Cañasgordas',1,5),
                    (179,'Cepita',1,68),
                    (180,'Cereté',1,23),
                    (181,'Cerinza',1,15),
                    (182,'Cerrito',1,68),
                    (183,'Cerro San Antonio',1,47),
                    (184,'Chachaguí',1,52),
                    (185,'Chaguaní',1,25),
                    (186,'Chalán',1,70),
                    (187,'Chaparral',1,73),
                    (188,'Charalá',1,68),
                    (189,'Charta',1,68),
                    (190,'Chigorodó',1,5),
                    (191,'Chima',1,68),
                    (192,'Chimichagua',1,20),
                    (193,'Chimá',1,23),
                    (194,'Chinavita',1,15),
                    (195,'Chinchiná',1,17),
                    (196,'Chinácota',1,54),
                    (197,'Chinú',1,23),
                    (198,'Chipaque',1,25),
                    (199,'Chipatá',1,68),
                    (200,'Chiquinquirá',1,15),
                    (201,'Chiriguaná',1,20),
                    (202,'Chiscas',1,15),
                    (203,'Chita',1,15),
                    (204,'Chitagá',1,54),
                    (205,'Chitaraque',1,15),
                    (206,'Chivatá',1,15),
                    (207,'Chivolo',1,47),
                    (208,'Choachí',1,25),
                    (209,'Chocontá',1,25),
                    (210,'Chámeza',1,85),
                    (211,'Chía',1,25),
                    (212,'Chíquiza',1,15),
                    (213,'Chívor',1,15),
                    (214,'Cicuco',1,13),
                    (215,'Cimitarra',1,68),
                    (216,'Circasia',1,63),
                    (217,'Cisneros',1,5),
                    (218,'Ciénaga',1,15),
                    (219,'Ciénaga',1,47),
                    (220,'Ciénaga de Oro',1,23),
                    (221,'Clemencia',1,13),
                    (222,'Cocorná',1,5),
                    (223,'Coello',1,73),
                    (224,'Cogua',1,25),
                    (225,'Colombia',1,41),
                    (226,'Colosó (Ricaurte)',1,70),
                    (227,'Colón',1,86),
                    (228,'Colón (Génova)',1,52),
                    (229,'Concepción',1,5),
                    (230,'Concepción',1,68),
                    (231,'Concordia',1,5),
                    (232,'Concordia',1,47),
                    (233,'Condoto',1,27),
                    (234,'Confines',1,68),
                    (235,'Consaca',1,52),
                    (236,'Contadero',1,52),
                    (237,'Contratación',1,68),
                    (238,'Convención',1,54),
                    (239,'Copacabana',1,5),
                    (240,'Coper',1,15),
                    (241,'Cordobá',1,63),
                    (242,'Corinto',1,19),
                    (243,'Coromoro',1,68),
                    (244,'Corozal',1,70),
                    (245,'Corrales',1,15),
                    (246,'Cota',1,25),
                    (247,'Cotorra',1,23),
                    (248,'Covarachía',1,15),
                    (249,'Coveñas',1,70),
                    (250,'Coyaima',1,73),
                    (251,'Cravo Norte',1,81),
                    (252,'Cuaspud (Carlosama)',1,52),
                    (253,'Cubarral',1,50),
                    (254,'Cubará',1,15),
                    (255,'Cucaita',1,15),
                    (256,'Cucunubá',1,25),
                    (257,'Cucutilla',1,54),
                    (258,'Cuitiva',1,15),
                    (259,'Cumaral',1,50),
                    (260,'Cumaribo',1,99),
                    (261,'Cumbal',1,52),
                    (262,'Cumbitara',1,52),
                    (263,'Cunday',1,73),
                    (264,'Curillo',1,18),
                    (265,'Curití',1,68),
                    (266,'Curumaní',1,20),
                    (267,'Cáceres',1,5),
                    (268,'Cáchira',1,54),
                    (269,'Cácota',1,54),
                    (270,'Cáqueza',1,25),
                    (271,'Cértegui',1,27),
                    (272,'Cómbita',1,15),
                    (273,'Córdoba',1,13),
                    (274,'Córdoba',1,52),
                    (275,'Cúcuta',1,54),
                    (276,'Dabeiba',1,5),
                    (277,'Dagua',1,76),
                    (278,'Dibulla',1,44),
                    (279,'Distracción',1,44),
                    (280,'Dolores',1,73),
                    (281,'Don Matías',1,5),
                    (282,'Dos Quebradas',1,66),
                    (283,'Duitama',1,15),
                    (284,'Durania',1,54),
                    (285,'Ebéjico',1,5),
                    (286,'El Bagre',1,5),
                    (287,'El Banco',1,47),
                    (288,'El Cairo',1,76),
                    (289,'El Calvario',1,50),
                    (290,'El Carmen',1,54),
                    (291,'El Carmen',1,68),
                    (292,'El Carmen de Atrato',1,27),
                    (293,'El Carmen de Bolívar',1,13),
                    (294,'El Castillo',1,50),
                    (295,'El Cerrito',1,76),
                    (296,'El Charco',1,52),
                    (297,'El Cocuy',1,15),
                    (298,'El Colegio',1,25),
                    (299,'El Copey',1,20),
                    (300,'El Doncello',1,18),
                    (301,'El Dorado',1,50),
                    (302,'El Dovio',1,76),
                    (303,'El Espino',1,15),
                    (304,'El Guacamayo',1,68),
                    (305,'El Guamo',1,13),
                    (306,'El Molino',1,44),
                    (307,'El Paso',1,20),
                    (308,'El Paujil',1,18),
                    (309,'El Peñol',1,52),
                    (310,'El Peñon',1,13),
                    (311,'El Peñon',1,68),
                    (312,'El Peñón',1,25),
                    (313,'El Piñon',1,47),
                    (314,'El Playón',1,68),
                    (315,'El Retorno',1,95),
                    (316,'El Retén',1,47),
                    (317,'El Roble',1,70),
                    (318,'El Rosal',1,25),
                    (319,'El Rosario',1,52),
                    (320,'El Tablón de Gómez',1,52),
                    (321,'El Tambo',1,19),
                    (322,'El Tambo',1,52),
                    (323,'El Tarra',1,54),
                    (324,'El Zulia',1,54),
                    (325,'El Águila',1,76),
                    (326,'Elías',1,41),
                    (327,'Encino',1,68),
                    (328,'Enciso',1,68),
                    (329,'Entrerríos',1,5),
                    (330,'Envigado',1,5),
                    (331,'Espinal',1,73),
                    (332,'Facatativá',1,25),
                    (333,'Falan',1,73),
                    (334,'Filadelfia',1,17),
                    (335,'Filandia',1,63),
                    (336,'Firavitoba',1,15),
                    (337,'Flandes',1,73),
                    (338,'Florencia',1,18),
                    (339,'Florencia',1,19),
                    (340,'Floresta',1,15),
                    (341,'Florida',1,76),
                    (342,'Floridablanca',1,68),
                    (343,'Florián',1,68),
                    (344,'Fonseca',1,44),
                    (345,'Fortúl',1,81),
                    (346,'Fosca',1,25),
                    (347,'Francisco Pizarro',1,52),
                    (348,'Fredonia',1,5),
                    (349,'Fresno',1,73),
                    (350,'Frontino',1,5),
                    (351,'Fuente de Oro',1,50),
                    (352,'Fundación',1,47),
                    (353,'Funes',1,52),
                    (354,'Funza',1,25),
                    (355,'Fusagasugá',1,25),
                    (356,'Fómeque',1,25),
                    (357,'Fúquene',1,25),
                    (358,'Gachalá',1,25),
                    (359,'Gachancipá',1,25),
                    (360,'Gachantivá',1,15),
                    (361,'Gachetá',1,25),
                    (362,'Galapa',1,8),
                    (363,'Galeras (Nueva Granada)',1,70),
                    (364,'Galán',1,68),
                    (365,'Gama',1,25),
                    (366,'Gamarra',1,20),
                    (367,'Garagoa',1,15),
                    (368,'Garzón',1,41),
                    (369,'Gigante',1,41),
                    (370,'Ginebra',1,76),
                    (371,'Giraldo',1,5),
                    (372,'Girardot',1,25),
                    (373,'Girardota',1,5),
                    (374,'Girón',1,68),
                    (375,'Gonzalez',1,20),
                    (376,'Gramalote',1,54),
                    (377,'Granada',1,5),
                    (378,'Granada',1,25),
                    (379,'Granada',1,50),
                    (380,'Guaca',1,68),
                    (381,'Guacamayas',1,15),
                    (382,'Guacarí',1,76),
                    (383,'Guachavés',1,52),
                    (384,'Guachené',1,19),
                    (385,'Guachetá',1,25),
                    (386,'Guachucal',1,52),
                    (387,'Guadalupe',1,5),
                    (388,'Guadalupe',1,41),
                    (389,'Guadalupe',1,68),
                    (390,'Guaduas',1,25),
                    (391,'Guaitarilla',1,52),
                    (392,'Gualmatán',1,52),
                    (393,'Guamal',1,47),
                    (394,'Guamal',1,50),
                    (395,'Guamo',1,73),
                    (396,'Guapota',1,68),
                    (397,'Guapí',1,19),
                    (398,'Guaranda',1,70),
                    (399,'Guarne',1,5),
                    (400,'Guasca',1,25),
                    (401,'Guatapé',1,5),
                    (402,'Guataquí',1,25),
                    (403,'Guatavita',1,25),
                    (404,'Guateque',1,15),
                    (405,'Guavatá',1,68),
                    (406,'Guayabal de Siquima',1,25),
                    (407,'Guayabetal',1,25),
                    (408,'Guayatá',1,15),
                    (409,'Guepsa',1,68),
                    (410,'Guicán',1,15),
                    (411,'Gutiérrez',1,25),
                    (412,'Guática',1,66),
                    (413,'Gámbita',1,68),
                    (414,'Gámeza',1,15),
                    (415,'Génova',1,63),
                    (416,'Gómez Plata',1,5),
                    (417,'Hacarí',1,54),
                    (418,'Hatillo de Loba',1,13),
                    (419,'Hato',1,68),
                    (420,'Hato Corozal',1,85),
                    (421,'Hatonuevo',1,44),
                    (422,'Heliconia',1,5),
                    (423,'Herrán',1,54),
                    (424,'Herveo',1,73),
                    (425,'Hispania',1,5),
                    (426,'Hobo',1,41),
                    (427,'Honda',1,73),
                    (428,'Ibagué',1,73),
                    (429,'Icononzo',1,73),
                    (430,'Iles',1,52),
                    (431,'Imúes',1,52),
                    (432,'Inzá',1,19),
                    (433,'Inírida',1,94),
                    (434,'Ipiales',1,52),
                    (435,'Isnos',1,41),
                    (436,'Istmina',1,27),
                    (437,'Itagüí',1,5),
                    (438,'Ituango',1,5),
                    (439,'Izá',1,15),
                    (440,'Jambaló',1,19),
                    (441,'Jamundí',1,76),
                    (442,'Jardín',1,5),
                    (443,'Jenesano',1,15),
                    (444,'Jericó',1,5),
                    (445,'Jericó',1,15),
                    (446,'Jerusalén',1,25),
                    (447,'Jesús María',1,68),
                    (448,'Jordán',1,68),
                    (449,'Juan de Acosta',1,8),
                    (450,'Junín',1,25),
                    (451,'Juradó',1,27),
                    (452,'La Apartada y La Frontera',1,23),
                    (453,'La Argentina',1,41),
                    (454,'La Belleza',1,68),
                    (455,'La Calera',1,25),
                    (456,'La Capilla',1,15),
                    (457,'La Ceja',1,5),
                    (458,'La Celia',1,66),
                    (459,'La Cruz',1,52),
                    (460,'La Cumbre',1,76),
                    (461,'La Dorada',1,17),
                    (462,'La Esperanza',1,54),
                    (463,'La Estrella',1,5),
                    (464,'La Florida',1,52),
                    (465,'La Gloria',1,20),
                    (466,'La Jagua de Ibirico',1,20),
                    (467,'La Jagua del Pilar',1,44),
                    (468,'La Llanada',1,52),
                    (469,'La Macarena',1,50),
                    (470,'La Merced',1,17),
                    (471,'La Mesa',1,25),
                    (472,'La Montañita',1,18),
                    (473,'La Palma',1,25),
                    (474,'La Paz',1,68),
                    (475,'La Paz (Robles)',1,20),
                    (476,'La Peña',1,25),
                    (477,'La Pintada',1,5),
                    (478,'La Plata',1,41),
                    (479,'La Playa',1,54),
                    (480,'La Primavera',1,99),
                    (481,'La Salina',1,85),
                    (482,'La Sierra',1,19),
                    (483,'La Tebaida',1,63),
                    (484,'La Tola',1,52),
                    (485,'La Unión',1,5),
                    (486,'La Unión',1,52),
                    (487,'La Unión',1,70),
                    (488,'La Unión',1,76),
                    (489,'La Uvita',1,15),
                    (490,'La Vega',1,19),
                    (491,'La Vega',1,25),
                    (492,'La Victoria',1,15),
                    (493,'La Victoria',1,17),
                    (494,'La Victoria',1,76),
                    (495,'La Virginia',1,66),
                    (496,'Labateca',1,54),
                    (497,'Labranzagrande',1,15),
                    (498,'Landázuri',1,68),
                    (499,'Lebrija',1,68),
                    (500,'Leiva',1,52),
                    (501,'Lejanías',1,50),
                    (502,'Lenguazaque',1,25),
                    (503,'Leticia',1,91),
                    (504,'Liborina',1,5),
                    (505,'Linares',1,52),
                    (506,'Lloró',1,27),
                    (507,'Lorica',1,23),
                    (508,'Los Córdobas',1,23),
                    (509,'Los Palmitos',1,70),
                    (510,'Los Patios',1,54),
                    (511,'Los Santos',1,68),
                    (512,'Lourdes',1,54),
                    (513,'Luruaco',1,8),
                    (514,'Lérida',1,73),
                    (515,'Líbano',1,73),
                    (516,'López (Micay)',1,19),
                    (517,'Macanal',1,15),
                    (518,'Macaravita',1,68),
                    (519,'Maceo',1,5),
                    (520,'Machetá',1,25),
                    (521,'Madrid',1,25),
                    (522,'Magangué',1,13),
                    (523,'Magüi (Payán)',1,52),
                    (524,'Mahates',1,13),
                    (525,'Maicao',1,44),
                    (526,'Majagual',1,70),
                    (527,'Malambo',1,8),
                    (528,'Mallama (Piedrancha)',1,52),
                    (529,'Manatí',1,8),
                    (530,'Manaure',1,44),
                    (531,'Manaure Balcón del Cesar',1,20),
                    (532,'Manizales',1,17),
                    (533,'Manta',1,25),
                    (534,'Manzanares',1,17),
                    (535,'Maní',1,85),
                    (536,'Mapiripan',1,50),
                    (537,'Margarita',1,13),
                    (538,'Marinilla',1,5),
                    (539,'Maripí',1,15),
                    (540,'Mariquita',1,73),
                    (541,'Marmato',1,17),
                    (542,'Marquetalia',1,17),
                    (543,'Marsella',1,66),
                    (544,'Marulanda',1,17),
                    (545,'María la Baja',1,13),
                    (546,'Matanza',1,68),
                    (547,'Medellín',1,5),
                    (548,'Medina',1,25),
                    (549,'Medio Atrato',1,27),
                    (550,'Medio Baudó',1,27),
                    (551,'Medio San Juan (ANDAGOYA)',1,27),
                    (552,'Melgar',1,73),
                    (553,'Mercaderes',1,19),
                    (554,'Mesetas',1,50),
                    (555,'Milán',1,18),
                    (556,'Miraflores',1,15),
                    (557,'Miraflores',1,95),
                    (558,'Miranda',1,19),
                    (559,'Mistrató',1,66),
                    (560,'Mitú',1,97),
                    (561,'Mocoa',1,86),
                    (562,'Mogotes',1,68),
                    (563,'Molagavita',1,68),
                    (564,'Momil',1,23),
                    (565,'Mompós',1,13),
                    (566,'Mongua',1,15),
                    (567,'Monguí',1,15),
                    (568,'Moniquirá',1,15),
                    (569,'Montebello',1,5),
                    (570,'Montecristo',1,13),
                    (571,'Montelíbano',1,23),
                    (572,'Montenegro',1,63),
                    (573,'Monteria',1,23),
                    (574,'Monterrey',1,85),
                    (575,'Morales',1,13),
                    (576,'Morales',1,19),
                    (577,'Morelia',1,18),
                    (578,'Morroa',1,70),
                    (579,'Mosquera',1,25),
                    (580,'Mosquera',1,52),
                    (581,'Motavita',1,15),
                    (582,'Moñitos',1,23),
                    (583,'Murillo',1,73),
                    (584,'Murindó',1,5),
                    (585,'Mutatá',1,5),
                    (586,'Mutiscua',1,54),
                    (587,'Muzo',1,15),
                    (588,'Málaga',1,68),
                    (589,'Nariño',1,5),
                    (590,'Nariño',1,25),
                    (591,'Nariño',1,52),
                    (592,'Natagaima',1,73),
                    (593,'Nechí',1,5),
                    (594,'Necoclí',1,5),
                    (595,'Neira',1,17),
                    (596,'Neiva',1,41),
                    (597,'Nemocón',1,25),
                    (598,'Nilo',1,25),
                    (599,'Nimaima',1,25),
                    (600,'Nobsa',1,15),
                    (601,'Nocaima',1,25),
                    (602,'Norcasia',1,17),
                    (603,'Norosí',1,13),
                    (604,'Novita',1,27),
                    (605,'Nueva Granada',1,47),
                    (606,'Nuevo Colón',1,15),
                    (607,'Nunchía',1,85),
                    (608,'Nuquí',1,27),
                    (609,'Nátaga',1,41),
                    (610,'Obando',1,76),
                    (611,'Ocamonte',1,68),
                    (612,'Ocaña',1,54),
                    (613,'Oiba',1,68),
                    (614,'Oicatá',1,15),
                    (615,'Olaya',1,5),
                    (616,'Olaya Herrera',1,52),
                    (617,'Onzaga',1,68),
                    (618,'Oporapa',1,41),
                    (619,'Orito',1,86),
                    (620,'Orocué',1,85),
                    (621,'Ortega',1,73),
                    (622,'Ospina',1,52),
                    (623,'Otanche',1,15),
                    (624,'Ovejas',1,70),
                    (625,'Pachavita',1,15),
                    (626,'Pacho',1,25),
                    (627,'Padilla',1,19),
                    (628,'Paicol',1,41),
                    (629,'Pailitas',1,20),
                    (630,'Paime',1,25),
                    (631,'Paipa',1,15),
                    (632,'Pajarito',1,15),
                    (633,'Palermo',1,41),
                    (634,'Palestina',1,17),
                    (635,'Palestina',1,41),
                    (636,'Palmar',1,68),
                    (637,'Palmar de Varela',1,8),
                    (638,'Palmas del Socorro',1,68),
                    (639,'Palmira',1,76),
                    (640,'Palmito',1,70),
                    (641,'Palocabildo',1,73),
                    (642,'Pamplona',1,54),
                    (643,'Pamplonita',1,54),
                    (644,'Pandi',1,25),
                    (645,'Panqueba',1,15),
                    (646,'Paratebueno',1,25),
                    (647,'Pasca',1,25),
                    (648,'Patía (El Bordo)',1,19),
                    (649,'Pauna',1,15),
                    (650,'Paya',1,15),
                    (651,'Paz de Ariporo',1,85),
                    (652,'Paz de Río',1,15),
                    (653,'Pedraza',1,47),
                    (654,'Pelaya',1,20),
                    (655,'Pensilvania',1,17),
                    (656,'Peque',1,5),
                    (657,'Pereira',1,66),
                    (658,'Pesca',1,15),
                    (659,'Peñol',1,5),
                    (660,'Piamonte',1,19),
                    (661,'Pie de Cuesta',1,68),
                    (662,'Piedras',1,73),
                    (663,'Piendamó',1,19),
                    (664,'Pijao',1,63),
                    (665,'Pijiño',1,47),
                    (666,'Pinchote',1,68),
                    (667,'Pinillos',1,13),
                    (668,'Piojo',1,8),
                    (669,'Pisva',1,15),
                    (670,'Pital',1,41),
                    (671,'Pitalito',1,41),
                    (672,'Pivijay',1,47),
                    (673,'Planadas',1,73),
                    (674,'Planeta Rica',1,23),
                    (675,'Plato',1,47),
                    (676,'Policarpa',1,52),
                    (677,'Polonuevo',1,8),
                    (678,'Ponedera',1,8),
                    (679,'Popayán',1,19),
                    (680,'Pore',1,85),
                    (681,'Potosí',1,52),
                    (682,'Pradera',1,76),
                    (683,'Prado',1,73),
                    (684,'Providencia',1,52),
                    (685,'Providencia',1,88),
                    (686,'Pueblo Bello',1,20),
                    (687,'Pueblo Nuevo',1,23),
                    (688,'Pueblo Rico',1,66),
                    (689,'Pueblorrico',1,5),
                    (690,'Puebloviejo',1,47),
                    (691,'Puente Nacional',1,68),
                    (692,'Puerres',1,52),
                    (693,'Puerto Asís',1,86),
                    (694,'Puerto Berrío',1,5),
                    (695,'Puerto Boyacá',1,15),
                    (696,'Puerto Caicedo',1,86),
                    (697,'Puerto Carreño',1,99),
                    (698,'Puerto Colombia',1,8),
                    (699,'Puerto Concordia',1,50),
                    (700,'Puerto Escondido',1,23),
                    (701,'Puerto Gaitán',1,50),
                    (702,'Puerto Guzmán',1,86),
                    (703,'Puerto Leguízamo',1,86),
                    (704,'Puerto Libertador',1,23),
                    (705,'Puerto Lleras',1,50),
                    (706,'Puerto López',1,50),
                    (707,'Puerto Nare',1,5),
                    (708,'Puerto Nariño',1,91),
                    (709,'Puerto Parra',1,68),
                    (710,'Puerto Rico',1,18),
                    (711,'Puerto Rico',1,50),
                    (712,'Puerto Rondón',1,81),
                    (713,'Puerto Salgar',1,25),
                    (714,'Puerto Santander',1,54),
                    (715,'Puerto Tejada',1,19),
                    (716,'Puerto Triunfo',1,5),
                    (717,'Puerto Wilches',1,68),
                    (718,'Pulí',1,25),
                    (719,'Pupiales',1,52),
                    (720,'Puracé (Coconuco)',1,19),
                    (721,'Purificación',1,73),
                    (722,'Purísima',1,23),
                    (723,'Pácora',1,17),
                    (724,'Páez',1,15),
                    (725,'Páez (Belalcazar)',1,19),
                    (726,'Páramo',1,68),
                    (727,'Quebradanegra',1,25),
                    (728,'Quetame',1,25),
                    (729,'Quibdó',1,27),
                    (730,'Quimbaya',1,63),
                    (731,'Quinchía',1,66),
                    (732,'Quipama',1,15),
                    (733,'Quipile',1,25),
                    (734,'Ragonvalia',1,54),
                    (735,'Ramiriquí',1,15),
                    (736,'Recetor',1,85),
                    (737,'Regidor',1,13),
                    (738,'Remedios',1,5),
                    (739,'Remolino',1,47),
                    (740,'Repelón',1,8),
                    (741,'Restrepo',1,50),
                    (742,'Restrepo',1,76),
                    (743,'Retiro',1,5),
                    (744,'Ricaurte',1,25),
                    (745,'Ricaurte',1,52),
                    (746,'Rio Negro',1,68),
                    (747,'Rioblanco',1,73),
                    (748,'Riofrío',1,76),
                    (749,'Riohacha',1,44),
                    (750,'Risaralda',1,17),
                    (751,'Rivera',1,41),
                    (752,'Roberto Payán (San José)',1,52),
                    (753,'Roldanillo',1,76),
                    (754,'Roncesvalles',1,73),
                    (755,'Rondón',1,15),
                    (756,'Rosas',1,19),
                    (757,'Rovira',1,73),
                    (758,'Ráquira',1,15),
                    (759,'Río Iró',1,27),
                    (760,'Río Quito',1,27),
                    (761,'Río Sucio',1,17),
                    (762,'Río Viejo',1,13),
                    (763,'Río de oro',1,20),
                    (764,'Ríonegro',1,5),
                    (765,'Ríosucio',1,27),
                    (766,'Sabana de Torres',1,68),
                    (767,'Sabanagrande',1,8),
                    (768,'Sabanalarga',1,5),
                    (769,'Sabanalarga',1,8),
                    (770,'Sabanalarga',1,85),
                    (771,'Sabanas de San Angel (SAN ANGEL)',1,47),
                    (772,'Sabaneta',1,5),
                    (773,'Saboyá',1,15),
                    (774,'Sahagún',1,23),
                    (775,'Saladoblanco',1,41),
                    (776,'Salamina',1,17),
                    (777,'Salamina',1,47),
                    (778,'Salazar',1,54),
                    (779,'Saldaña',1,73),
                    (780,'Salento',1,63),
                    (781,'Salgar',1,5),
                    (782,'Samacá',1,15),
                    (783,'Samaniego',1,52),
                    (784,'Samaná',1,17),
                    (785,'Sampués',1,70),
                    (786,'San Agustín',1,41),
                    (787,'San Alberto',1,20),
                    (788,'San Andrés',1,68),
                    (789,'San Andrés Sotavento',1,23),
                    (790,'San Andrés de Cuerquía',1,5),
                    (791,'San Antero',1,23),
                    (792,'San Antonio',1,73),
                    (793,'San Antonio de Tequendama',1,25),
                    (794,'San Benito',1,68),
                    (795,'San Benito Abad',1,70),
                    (796,'San Bernardo',1,25),
                    (797,'San Bernardo',1,52),
                    (798,'San Bernardo del Viento',1,23),
                    (799,'San Calixto',1,54),
                    (800,'San Carlos',1,5),
                    (801,'San Carlos',1,23),
                    (802,'San Carlos de Guaroa',1,50),
                    (803,'San Cayetano',1,25),
                    (804,'San Cayetano',1,54),
                    (805,'San Cristobal',1,13),
                    (806,'San Diego',1,20),
                    (807,'San Eduardo',1,15),
                    (808,'San Estanislao',1,13),
                    (809,'San Fernando',1,13),
                    (810,'San Francisco',1,5),
                    (811,'San Francisco',1,25),
                    (812,'San Francisco',1,86),
                    (813,'San Gíl',1,68),
                    (814,'San Jacinto',1,13),
                    (815,'San Jacinto del Cauca',1,13),
                    (816,'San Jerónimo',1,5),
                    (817,'San Joaquín',1,68),
                    (818,'San José',1,17),
                    (819,'San José de Miranda',1,68),
                    (820,'San José de Montaña',1,5),
                    (821,'San José de Pare',1,15),
                    (822,'San José de Uré',1,23),
                    (823,'San José del Fragua',1,18),
                    (824,'San José del Guaviare',1,95),
                    (825,'San José del Palmar',1,27),
                    (826,'San Juan de Arama',1,50),
                    (827,'San Juan de Betulia',1,70),
                    (828,'San Juan de Nepomuceno',1,13),
                    (829,'San Juan de Pasto',1,52),
                    (830,'San Juan de Río Seco',1,25),
                    (831,'San Juan de Urabá',1,5),
                    (832,'San Juan del Cesar',1,44),
                    (833,'San Juanito',1,50),
                    (834,'San Lorenzo',1,52),
                    (835,'San Luis',1,73),
                    (836,'San Luís',1,5),
                    (837,'San Luís de Gaceno',1,15),
                    (838,'San Luís de Palenque',1,85),
                    (839,'San Marcos',1,70),
                    (840,'San Martín',1,20),
                    (841,'San Martín',1,50),
                    (842,'San Martín de Loba',1,13),
                    (843,'San Mateo',1,15),
                    (844,'San Miguel',1,68),
                    (845,'San Miguel',1,86),
                    (846,'San Miguel de Sema',1,15),
                    (847,'San Onofre',1,70),
                    (848,'San Pablo',1,13),
                    (849,'San Pablo',1,52),
                    (850,'San Pablo de Borbur',1,15),
                    (851,'San Pedro',1,5),
                    (852,'San Pedro',1,70),
                    (853,'San Pedro',1,76),
                    (854,'San Pedro de Cartago',1,52),
                    (855,'San Pedro de Urabá',1,5),
                    (856,'San Pelayo',1,23),
                    (857,'San Rafael',1,5),
                    (858,'San Roque',1,5),
                    (859,'San Sebastián',1,19),
                    (860,'San Sebastián de Buenavista',1,47),
                    (861,'San Vicente',1,5),
                    (862,'San Vicente del Caguán',1,18),
                    (863,'San Vicente del Chucurí',1,68),
                    (864,'San Zenón',1,47),
                    (865,'Sandoná',1,52),
                    (866,'Santa Ana',1,47),
                    (867,'Santa Bárbara',1,5),
                    (868,'Santa Bárbara',1,68),
                    (869,'Santa Bárbara (Iscuandé)',1,52),
                    (870,'Santa Bárbara de Pinto',1,47),
                    (871,'Santa Catalina',1,13),
                    (872,'Santa Fé de Antioquia',1,5),
                    (873,'Santa Genoveva de Docorodó',1,27),
                    (874,'Santa Helena del Opón',1,68),
                    (875,'Santa Isabel',1,73),
                    (876,'Santa Lucía',1,8),
                    (877,'Santa Marta',1,47),
                    (878,'Santa María',1,15),
                    (879,'Santa María',1,41),
                    (880,'Santa Rosa',1,13),
                    (881,'Santa Rosa',1,19),
                    (882,'Santa Rosa de Cabal',1,66),
                    (883,'Santa Rosa de Osos',1,5),
                    (884,'Santa Rosa de Viterbo',1,15),
                    (885,'Santa Rosa del Sur',1,13),
                    (886,'Santa Rosalía',1,99),
                    (887,'Santa Sofía',1,15),
                    (888,'Santana',1,15),
                    (889,'Santander de Quilichao',1,19),
                    (890,'Santiago',1,54),
                    (891,'Santiago',1,86),
                    (892,'Santo Domingo',1,5),
                    (893,'Santo Tomás',1,8),
                    (894,'Santuario',1,5),
                    (895,'Santuario',1,66),
                    (896,'Sapuyes',1,52),
                    (897,'Saravena',1,81),
                    (898,'Sardinata',1,54),
                    (899,'Sasaima',1,25),
                    (900,'Sativanorte',1,15),
                    (901,'Sativasur',1,15),
                    (902,'Segovia',1,5),
                    (903,'Sesquilé',1,25),
                    (904,'Sevilla',1,76),
                    (905,'Siachoque',1,15),
                    (906,'Sibaté',1,25),
                    (907,'Sibundoy',1,86),
                    (908,'Silos',1,54),
                    (909,'Silvania',1,25),
                    (910,'Silvia',1,19),
                    (911,'Simacota',1,68),
                    (912,'Simijaca',1,25),
                    (913,'Simití',1,13),
                    (914,'Sincelejo',1,70),
                    (915,'Sincé',1,70),
                    (916,'Sipí',1,27),
                    (917,'Sitionuevo',1,47),
                    (918,'Soacha',1,25),
                    (919,'Soatá',1,15),
                    (920,'Socha',1,15),
                    (921,'Socorro',1,68),
                    (922,'Socotá',1,15),
                    (923,'Sogamoso',1,15),
                    (924,'Solano',1,18),
                    (925,'Soledad',1,8),
                    (926,'Solita',1,18),
                    (927,'Somondoco',1,15),
                    (928,'Sonsón',1,5),
                    (929,'Sopetrán',1,5),
                    (930,'Soplaviento',1,13),
                    (931,'Sopó',1,25),
                    (932,'Sora',1,15),
                    (933,'Soracá',1,15),
                    (934,'Sotaquirá',1,15),
                    (935,'Sotara (Paispamba)',1,19),
                    (936,'Sotomayor (Los Andes)',1,52),
                    (937,'Suaita',1,68),
                    (938,'Suan',1,8),
                    (939,'Suaza',1,41),
                    (940,'Subachoque',1,25),
                    (941,'Sucre',1,19),
                    (942,'Sucre',1,68),
                    (943,'Sucre',1,70),
                    (944,'Suesca',1,25),
                    (945,'Supatá',1,25),
                    (946,'Supía',1,17),
                    (947,'Suratá',1,68),
                    (948,'Susa',1,25),
                    (949,'Susacón',1,15),
                    (950,'Sutamarchán',1,15),
                    (951,'Sutatausa',1,25),
                    (952,'Sutatenza',1,15),
                    (953,'Suárez',1,19),
                    (954,'Suárez',1,73),
                    (955,'Sácama',1,85),
                    (956,'Sáchica',1,15),
                    (957,'Tabio',1,25),
                    (958,'Tadó',1,27),
                    (959,'Talaigua Nuevo',1,13),
                    (960,'Tamalameque',1,20),
                    (961,'Tame',1,81),
                    (962,'Taminango',1,52),
                    (963,'Tangua',1,52),
                    (964,'Taraira',1,97),
                    (965,'Tarazá',1,5),
                    (966,'Tarqui',1,41),
                    (967,'Tarso',1,5),
                    (968,'Tasco',1,15),
                    (969,'Tauramena',1,85),
                    (970,'Tausa',1,25),
                    (971,'Tello',1,41),
                    (972,'Tena',1,25),
                    (973,'Tenerife',1,47),
                    (974,'Tenjo',1,25),
                    (975,'Tenza',1,15),
                    (976,'Teorama',1,54),
                    (977,'Teruel',1,41),
                    (978,'Tesalia',1,41),
                    (979,'Tibacuy',1,25),
                    (980,'Tibaná',1,15),
                    (981,'Tibasosa',1,15),
                    (982,'Tibirita',1,25),
                    (983,'Tibú',1,54),
                    (984,'Tierralta',1,23),
                    (985,'Timaná',1,41),
                    (986,'Timbiquí',1,19),
                    (987,'Timbío',1,19),
                    (988,'Tinjacá',1,15),
                    (989,'Tipacoque',1,15),
                    (990,'Tiquisio (Puerto Rico)',1,13),
                    (991,'Titiribí',1,5),
                    (992,'Toca',1,15),
                    (993,'Tocaima',1,25),
                    (994,'Tocancipá',1,25),
                    (995,'Toguí',1,15),
                    (996,'Toledo',1,5),
                    (997,'Toledo',1,54),
                    (998,'Tolú',1,70),
                    (999,'Tolú Viejo',1,70),
                    (1000,'Tona',1,68),
                    (1001,'Topagá',1,15),
                    (1002,'Topaipí',1,25),
                    (1003,'Toribío',1,19),
                    (1004,'Toro',1,76),
                    (1005,'Tota',1,15),
                    (1006,'Totoró',1,19),
                    (1007,'Trinidad',1,85),
                    (1008,'Trujillo',1,76),
                    (1009,'Tubará',1,8),
                    (1010,'Tuchín',1,23),
                    (1011,'Tulúa',1,76),
                    (1012,'Tumaco',1,52),
                    (1013,'Tunja',1,15),
                    (1014,'Tunungua',1,15),
                    (1015,'Turbaco',1,13),
                    (1016,'Turbaná',1,13),
                    (1017,'Turbo',1,5),
                    (1018,'Turmequé',1,15),
                    (1019,'Tuta',1,15),
                    (1020,'Tutasá',1,15),
                    (1021,'Támara',1,85),
                    (1022,'Támesis',1,5),
                    (1023,'Túquerres',1,52),
                    (1024,'Ubalá',1,25),
                    (1025,'Ubaque',1,25),
                    (1026,'Ubaté',1,25),
                    (1027,'Ulloa',1,76),
                    (1028,'Une',1,25),
                    (1029,'Unguía',1,27),
                    (1030,'Unión Panamericana (ÁNIMAS)',1,27),
                    (1031,'Uramita',1,5),
                    (1032,'Uribe',1,50),
                    (1033,'Uribia',1,44),
                    (1034,'Urrao',1,5),
                    (1035,'Urumita',1,44),
                    (1036,'Usiacuri',1,8),
                    (1037,'Valdivia',1,5),
                    (1038,'Valencia',1,23),
                    (1039,'Valle de San José',1,68),
                    (1040,'Valle de San Juan',1,73),
                    (1041,'Valle del Guamuez',1,86),
                    (1042,'Valledupar',1,20),
                    (1043,'Valparaiso',1,5),
                    (1044,'Valparaiso',1,18),
                    (1045,'Vegachí',1,5),
                    (1046,'Venadillo',1,73),
                    (1047,'Venecia',1,5),
                    (1048,'Venecia (Ospina Pérez)',1,25),
                    (1049,'Ventaquemada',1,15),
                    (1050,'Vergara',1,25),
                    (1051,'Versalles',1,76),
                    (1052,'Vetas',1,68),
                    (1053,'Viani',1,25),
                    (1054,'Vigía del Fuerte',1,5),
                    (1055,'Vijes',1,76),
                    (1056,'Villa Caro',1,54),
                    (1057,'Villa Rica',1,19),
                    (1058,'Villa de Leiva',1,15),
                    (1059,'Villa del Rosario',1,54),
                    (1060,'Villagarzón',1,86),
                    (1061,'Villagómez',1,25),
                    (1062,'Villahermosa',1,73),
                    (1063,'Villamaría',1,17),
                    (1064,'Villanueva',1,13),
                    (1065,'Villanueva',1,44),
                    (1066,'Villanueva',1,68),
                    (1067,'Villanueva',1,85),
                    (1068,'Villapinzón',1,25),
                    (1069,'Villarrica',1,73),
                    (1070,'Villavicencio',1,50),
                    (1071,'Villavieja',1,41),
                    (1072,'Villeta',1,25),
                    (1073,'Viotá',1,25),
                    (1074,'Viracachá',1,15),
                    (1075,'Vista Hermosa',1,50),
                    (1076,'Viterbo',1,17),
                    (1077,'Vélez',1,68),
                    (1078,'Yacopí',1,25),
                    (1079,'Yacuanquer',1,52),
                    (1080,'Yaguará',1,41),
                    (1081,'Yalí',1,5),
                    (1082,'Yarumal',1,5),
                    (1083,'Yolombó',1,5),
                    (1084,'Yondó (Casabe)',1,5),
                    (1085,'Yopal',1,85),
                    (1086,'Yotoco',1,76),
                    (1087,'Yumbo',1,76),
                    (1088,'Zambrano',1,13),
                    (1089,'Zapatoca',1,68),
                    (1090,'Zapayán (PUNTA DE PIEDRAS)',1,47),
                    (1091,'Zaragoza',1,5),
                    (1092,'Zarzal',1,76),
                    (1093,'Zetaquirá',1,15),
                    (1094,'Zipacón',1,25),
                    (1095,'Zipaquirá',1,25),
                    (1096,'Zona Bananera (PRADO - SEVILLA)',1,47),
                    (1097,'Ábrego',1,54),
                    (1098,'Íquira',1,41),
                    (1099,'Úmbita',1,15),
                    (1100,'Útica',1,25),
                ]
                
                total = len(MUNICIPIOS)
                nuevas = 0
                actualizadas = 0
                errores = 0
                advertencias = 0

                for i in range(0, total, batch_size):
                    batch = MUNICIPIOS[i:i + batch_size]
                    ciudades = []
                    
                    for code, name, activo, state_code in batch:
                        try:
                            # Formatear códigos
                            state_code_str = str(state_code).zfill(2)
                            city_code_str = str(code).zfill(3)
                            
                            # Validar estado
                            estado = estados.get(state_code_str)
                            if not estado:
                                advertencias += 1
                                self.stdout.write(self.style.WARNING(
                                    f'⚠️ Estado {state_code_str} no encontrado para {city_code_str} {name}'
                                ))
                                continue

                            # Crear/actualizar ciudad
                            obj, created = City.objects.update_or_create(
                                code=city_code_str,
                                defaults={
                                    'name': name.strip().title(),
                                    'state': estado
                                }
                            )
                            
                            if created:
                                nuevas += 1
                                self.stdout.write(f'✓ Creada: {city_code_str} - {name}')
                            else:
                                actualizadas += 1
                                self.stdout.write(f'↻ Actualizada: {city_code_str} - {name}')

                        except ValueError as e:
                            errores += 1
                            self.stdout.write(self.style.ERROR(
                                f'❌ Error de valor en {code}-{name}: {str(e)}'
                            ))
                        except Exception as e:
                            errores += 1
                            self.stdout.write(self.style.ERROR(
                                f'❌ Error desconocido en {code}-{name}: {str(e)}'
                            ))

                    self.stdout.write(f'Procesado lote {(i//batch_size)+1}/{(total//batch_size)+1}')

                # Reporte final
                self.stdout.write("\n" + "="*50)
                self.stdout.write(self.style.SUCCESS(
                    f"✅ CARGA COMPLETADA: {nuevas} nuevas, {actualizadas} actualizadas"
                ))
                if advertencias:
                    self.stdout.write(self.style.WARNING(
                        f"⚠️ Advertencias: {advertencias} (relaciones faltantes)"
                    ))
                if errores:
                    self.stdout.write(self.style.ERROR(
                        f"❌ Errores: {errores}"
                    ))
                self.stdout.write("="*50 + "\n")

        except Exception as e:
            self.stdout.write(self.style.ERROR(
                f"🚨 ERROR GLOBAL: {str(e)}"
            ))
            raise CommandError("Carga interrumpida por error crítico") from e


