# Generated by Django 5.1.7 on 2025-04-26 00:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Año Fiscal')),
            ],
            options={
                'verbose_name': 'Período Contable',
                'verbose_name_plural': 'Períodos Contables',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa Personalizada')),
                ('applied_to', models.CharField(choices=[('SALES', 'Ventas'), ('PURCHASES', 'Compras'), ('BOTH', 'Ambos')], default='BOTH', max_length=20, verbose_name='Aplicado a')),
            ],
            options={
                'verbose_name': 'Configuración de Impuestos por Empresa',
                'verbose_name_plural': 'Configuraciones de Impuestos por Empresa',
            },
        ),
        migrations.CreateModel(
            name='CuentaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(default=5, verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_tax_account', models.BooleanField(default=False, verbose_name='Es cuenta fiscal')),
                ('allows_movements', models.BooleanField(default=True, verbose_name='Permite movimientos')),
            ],
            options={
                'verbose_name': 'Cuenta Auxiliar',
                'verbose_name_plural': 'Cuentas Auxiliares',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CuentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(default=4, verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_tax_account', models.BooleanField(default=False, verbose_name='Es cuenta fiscal')),
            ],
            options={
                'verbose_name': 'Cuenta Detalle',
                'verbose_name_plural': 'Cuentas Detalle',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cuenta Mayor',
                'verbose_name_plural': 'Cuentas Mayor',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Grupo de Cuenta',
                'verbose_name_plural': 'Grupos de Cuenta',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('INGRESO', 'Comprobantes de Ingreso'), ('EGRESO', 'Comprobantes de Egreso'), ('DIARIO', 'Comprobantes Diario'), ('VENTA', 'Facturas de Venta'), ('COMPRA', 'Facturas de Compra')], max_length=20, verbose_name='Tipo')),
                ('consecutive', models.PositiveIntegerField(default=1, verbose_name='Consecutivo Actual')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefijo')),
                ('resolution_number', models.CharField(blank=True, help_text='Número de resolución de numeración autorizada', max_length=50, verbose_name='Resolución DIAN')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Válido Desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
            ],
            options={
                'verbose_name': 'Diario Contable',
                'verbose_name_plural': 'Diarios Contables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('reference', models.CharField(help_text='Número de documento generado automáticamente', max_length=50, verbose_name='Referencia')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Contabilizado')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Conciliado')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-date', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('is_debit', models.BooleanField(default=True, verbose_name='Es Débito')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Base Gravable')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Naturaleza',
                'verbose_name_plural': 'Naturalezas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Subcuenta',
                'verbose_name_plural': 'Subcuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es predeterminado')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
            ],
            options={
                'verbose_name': 'Tasa de Impuesto',
                'verbose_name_plural': 'Tasas de Impuestos',
                'ordering': ['tax_type', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuestos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa')),
                ('min_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base mínima')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
            ],
            options={
                'verbose_name': 'Concepto de Retención',
                'verbose_name_plural': 'Conceptos de Retención',
                'ordering': ['withholding_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Retención',
                'verbose_name_plural': 'Tipos de Retención',
                'ordering': ['name'],
            },
        ),
    ]
