# Generated by Django 5.1.7 on 2025-04-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VIEW', 'Visualización'), ('OTHER', 'Otra acción')], max_length=20, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del objeto')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de tabla')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
